### ISSUE TITLE
Can't seem to customise grc with Homebrew. Am I doing something wrong?

### ISSUE THREAD

**Issue by interior-night** [pengwynn/grc#3]
I've asked this question on superuser.com but maybe this is the best place to seek help? So here is the question:

I've installed grc through Homebrew on Mavericks. I can't quite understand the readme. What I want to do, for example, is have the terminal output colourise the number at the start of each line when I type 'history' in my bash terminal.

As I could not find a grc.conf file in the homebrew install, i've created a ~/.grc folder, copied the grc.conf file from https://github.com/pengwynn/grc/ and placed it in ~/.grc and added the following code at the bottom:

```
# history
(^|[/\w\.]+/)history
conf.history
```

I've also created a conf.history file containing the following:

```
# colourise numbers
regexp=\d+\s{2}
colours=bold blue
count=stop
```

and placed it both in ~/.grc and /usr/local/Cellar/grc/1.5/share/grc (because i wasn't sure where it should go).

When I type 'history', I'm not getting any colours though. And when I type 'grc history' I get the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/grc", line 117, in <module> os.execvp(args[0], args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 344, in execvp execvpe(file, args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 380, in _execvpe func(fullname, *argrest)
OSError: [Errno 2] No such file or directory
```

Any help to get this happening correctly would be greatly appreciated!

**Comment by kevinSuttle** [comment]
I noticed that grc.conf [isn't being added to /etc/](https://github.com/Homebrew/homebrew/commit/fa93e72995f0f7c50e5319200920f3460b4b6dfa#commitcomment-4963762). Wondering if this has something to do with it.
