### ISSUE TITLE
Python Error, but native GRC works fine?

### ISSUE THREAD

**Issue by joshrhoades** [pengwynn/grc#6]
My last resort, after trolling through numerous other fixes, is this ticket, so hopefully this is not something painfully obvious that I've missed. When I invoke any aliased function to GRC, such as ping, I get the following error:

```
ping google.com
Traceback (most recent call last):
  File "/usr/local/bin/grc", line 161, in <module>
    os.execvp(args[0], args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 346, in execvp
    _execvpe(file, args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 382, in _execvpe
    func(fullname, *argrest)
OSError: [Errno 2] No such file or directory
```

I've updated all of brew, python, grc itself, had a permissions issue with how Apple is now handling software updates that changes permissions on usr local, and resolved it, etc., etc.

But the weird thing is if I do `grc ping google.com` it works fine.

The path `/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/` exists, but `os.py` does not.

I'm running OSX El Capitan 10.11.5, and this only popped up a few days ago after a software update, with no changes to bashprofile or anything else.

Python:

```
Python 2.7.11
python is /usr/local/bin/python
python is /usr/bin/python
```

GRC: 

```
Generic Colouriser 1.9
grc is /usr/local/bin/grc
```

My bash does have `source "`brew --prefix`/etc/grc.bashrc"` setup, and it is adding the aliases automatically as expected, such as

```
alias as='colourify as'
alias colourify='grc is /usr/local/bin/grc -es --colour=auto'
alias g++='colourify g++'
alias gas='colourify gas'
alias gcc='colourify gcc'
alias head='colourify head'
alias ld='colourify ld'
alias make='colourify make'
alias mount='colourify mount'
alias mtr='colourify mtr'
alias netstat='colourify netstat'
alias ping='colourify ping'
alias ps='colourify ps'
alias tail='colourify tail'
alias traceroute='colourify /usr/sbin/traceroute'
```

**Comment by inhies** [comment]
Same issue here

**Comment by atipugin** [comment]
Same here ;(
